### ISSUE TITLE
Layout fixes

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/VSBLE#18]
### Задача

Пофиксить все несостыковки с [дизайном](https://www.figma.com/file/19asuibedHRPdawvpWuPM7/VSBLE.space-%D0%B4%D0%BE-18.04.22?node-id=0%3A1)

Полный список - https://immers.notion.site/53783d70edc74dc7a3fb5d27b63a521b

### Чекпоинты

- [x] Съехавшая кнопка в футере
- [x] Цвет у Search placeholder
- [x] Посмотреть что не так с размером первой картинки в масонри. Либо пофиксить размеры контейнера, либо загрузить картинку с валидными размерами
- [x] Иконка стрелки в Select слишком большая (анимации пока делать)
- [x] Съехал дефис между min и max в фильтрах
- [x] Select: Не хватает отступа между плашкой и полем, большие отступы в списке, при клике поле должно быть белым
- [x] Сравнить галочку в checkbox с дизайном и пофиксить размер/placement
- [x] Проверить disabled состояние у Select
- [x] У вкладок нету ховера
- [x] Нету ховера у фиолетовой кнопки в масонри итеме
- [x] Масонри итем болжен затемняться при ховере
- [x] У кнопки не закрашивается иконка при ховере
- [x] Добавить ховеры для крестика и стрелки
- [x] Добавить ховер для иконки i
- [x] Сделать триггер на ховер
- [x] Пофиксить размер иконки i чтобы стрелка от тултипа была ровно по середине
- [x] Отступ в дропдауне multiselect

**Comment by BRUSSELMINEFIVENINE** [comment]
## Цвет у Search placeholder
@TFK70 

На данный момент цвет текста placeholder отличается от того, который в дизайне.
Сам инпут с проблемным [плейсхолдером](https://github.com/torin-asakura/VSBLE/blob/fix/finalize-styles/site/fragments/filters/src/filters.component.tsx#L98)

## Что сделал

в [baseStyles](https://github.com/torin-asakura/VSBLE/pull/19/files#diff-3c79dc6bda76ca80176a115c1b1a96ffd6f27c72e6ddecea77146458747e4bf7R34-R41), добавил стили для input placeholder, но они не применяются, максимум что получалось сделать это поменять цвет текста у самого инпута, но не у плейсхолдера.

Также в ui/theme/src/theme/colors имеется описаны цвета по каждый случай для [инпута](https://github.com/torin-asakura/VSBLE/blob/fix/finalize-styles/ui/theme/src/theme/colors.ts#L231-L250), там задается цвет для placeholder, но в стилизации инпута для [appearanceGhostStyles](https://github.com/torin-asakura/VSBLE/blob/fix/finalize-styles/ui/input/src/input.styles.ts#L56-L72) он не используется
